---
title: "CFA Level 1: Quantitative Methods (part 3)"
slug: cfa-level-1-quantitative-methods-part-3
description: ""
date: "`r Sys.time()`"
categories:
- CFA Level 1
tags:
- Quantitative Methods
tags_weight: 3
output:
      blogdown::html_page:
            toc: true
summary: "Quantitative methods covers statistical topics including descriptive statistics, hypothesis testing, and more."
thumbnail: ""
---

## Statistical Inference	

* Hypothesis Testing (testing validity of parameters)													
Estimation (estimation of parameters)														
														
Sampling Bias														
Data Mining														
??? Out-of-Sample Test: using a sample that does not overlap the time period of the variable under consideration														
??? Intergenerational Data Mining: repeatedly using data produced by prior researchers until a pattern is discovered														
??? A data-mining bias occurs when variables are added to an analysis without any predictive merit (i.e., there is no causal relationship for adding the variables). The variables are not added to enhance prediction, but to thwart the predictive relationship between other variables.														
														
Sample Selection Bias														
Using data availability as a criteria for sampling														
														
Survivorship Bias														
Excluding data that is discontinued (defaulted firms)														
														
Look-ahead Bias														
Using data that is not currently available to every market participant														
														
Time-period Bias														
Using data that is inherently influenced by a specific time-period that skews the results														
														
## Estimators		
"UEC"											
* Unbiased				
      * The expected value of the estimator equals the value of the parameter			
* Efficient					
      * The variance of the estimator is the least of all other estimators of the parameter						
* Consistent					
      * The probability that the estimator equals the paramater increases with increasing sample size														
														
## Skewed Distribution	

No Skew:      Mode = Median = Mean														
Left Skew:    Mode > Median > Mean														
Right Skew:  Mode < Median < Mean														
														
	Z	Confidence	Z	Confidence										
	1.65	90%	1	68%										
	1.96	95%	2	95%										
	2.58	99%	3	99%										
														
Confidence Interval 														
Probabilistic interpretation:  __% of the resulting confidence intervals will, in the long run, contain the population parameter														
Practical interpretation:  We are __% confident the given confidence interval contains the population parameter														
														
Total Probability Rule														
Pr(A) = Pr(A|B)Pr(B) + Pr(A|C)Pr(C)														
														
Addtion Rule of Probability														
Pr(A or B) = Pr(A) + Pr(B) - Pr(A and B)														
														
Multiplication Rule of Probability														
Pr(A and B) = Pr(A)Pr(B)														
														
Steps in Hypothesis Testing														
1. State hypothesis														
2. Decide on test statistics and probability distribution														
3. Decide on significance level														
4. Decide on decision rule														
5. Collect data and calculate test statistic														
6. Make statistical decision														
7. Make economic decision														
														
Power of  a Test														
The probability of rejecting a false null hypothesis														
Power = 1-$\beta$ = 1-Pr(Type II error)														
														
Labeling														
How many ways can k labels can be assigned to n items														
The number of items that receive label 1 is n1, where n1+n2+n3+.+nk = n														
														
														
														
														
														
Test for Population Mean (Z-stat)														
Assumptions:														
Known variance (or unknown if n>30)														
Normal distribution (or nonnormal if n>30)														
														
Test for Population Mean (T-Stat)														
Assumptions:														
Unknown variance and...														
Either														
1. sample is large (n>30) or...														
2. sample is small, but the population is at least approximately normally distributed														
														
Test of Mean Differences (T Statistic)														
Assumptions:														
Normally distributed populations														
Unknown population variances														
Test for Difference Between Means (t-stat)														
Assumptions: 														
Normally distributed populations,														
Independent populations														
Population variances unknown, but assumed equal														
														
														
														
														
														
														
df = n1+n2-2														
														
														
														
														
														
Assumptions:														
Normally distributed populations														
Independent populations														
Unequal and unknown populatino variances														
														
														
														
														
														
														
														
														
														
														
														
														
														
In majority of cases, the T-test is used!														
														
Assumptions:														
Normally distributed populations														
Dependent populations														
														
														
														
														
														
Stocks are generally considered to be dependent (both rely on market returns)														
														
		Test Statistic												
When sampling from a:		Small Sample	Large Sample											
		n<30	n>30											
Normal distribution, known variance		z	z											
														
Normal distribution, unknown  variance		t	t or z											
														
Nonnormal distribution, known variance		not available	z	Central Limit Theorem										
														
Nonnormal distribution,  unknown variance		not available	t or z	Central Limit Theorem										
														
														
Types of Risk														
Default risk - risk that a security will lose value due to a firm's default														
Liquidity risk - risk of receiving less than the fair value for an asset if it must be sold quickly														
Maturity risk - risk of higher volatility of longer maturity instruments (particularly with bonds)														
														
RRORbond = real risk-free rate + inflation premium + default risk premium + liquidity premium + maturity premium														
														
Test for Variance (1 population - $??^2$)														
Assumptions:														
Normally distributed population														
$??^2$ distribution approaches the normal distribution as the sample size increases											
## Test for Equality of Variances (2 populations - F-dist)	
* Assumptions:														
Normally distributed populations														
Independent distributions														
Rejection region is in the right tail of the F-distribution (if s21 is the greater sample variance)														
														
														
														
														
## Power of a Test			

* 1-P(Type II Error)														
  														
## Technical Analysis	
							
* Assumptions:
      * Value is determined by supply and demand
      * Supply and demand is driven by both rational and irrational behavior				
      * Prices move in trends that persist for long periods	

Causes of changes in supply and demand are difficult to determine														
## Main challenge to technical analysis is the EMH 

* Fundamentalists look for reasons why prices should change and realize the change when they find a reason for it to change		
EMH theory contends that prices adjust quickly to new information														
Technical analysts contend that prices adjust slowly to new information														
														
Almost without exception, EMH studies using autocorrelation and runs tests have found no evidence that prices move in trends. 														
														
Strategies								 						
Contrarian - most investors are wrong, so do the opposite														
Follow the smart money - "jumping on the bandwagon"														
														
Indictors														
Momentum indicators - focus on direction of market														
Price- and volume-based indicators - focus on market data														
														
														
## Contrarian Rules			

1. Cash position of mutual funds - need for liquidity (mutual fund ratio = mutual fund cash / total fund assets; a ratio > 11% suggests MF managers are bearish; a ratio < 4% suggests MF managers are bullish)						
2. Investor credit balances in brokerage accounts - need for liquidity (credit balances are uninvested cash)	
3. Opinions of investment advisory services - relative view of analysts			
4. Over-the-counter vs. NYSE volume - Over-the-counter trading is more speculative					
5. CBOE put/call ratio - puts outstanding/calls outstanding														
5.) Stock index futures - observe expected price growth														
														
Smart Money Rules														
Confidence index = quality bond yields/average bond yields														
														
In periods of confidence, investors sell high-quality bonds (increasing their yields) and buy lower-quality bonds (decreasing their yields), decreasing the yield spread														
														
In periods of pessimism, investors buy high-quality bonds (decreasing their yields) and sell lower-quality bonds (increasing their yields), increasing the yield spread														
														
														
T-bill-Eurodollar yield spread - measures international crises and use of U.S. safe havens														
Debit balances in brokerage accounts (margin debt)														
														
Momentum Indicators														
Breadth of market														
Stocks above their 200-day moving average														
														
Stock Price and Volume Techniques														
Dow Theory - stock prices move in trends														
Importance of volume - Price changes on low volume tell us little.  Price changes on high volume tell us whether suppliers or demanders are driving the change.														
														
Support and resistance levels														
Price Channels														
														
Relative Strength (RS) - RS = stock price / market index value														
														
Underlying technical analysis are the following assumptions:														
1) Values, and thus prices, are determined by supply and demand.														
2) Supply and demand are driven by both rational and irrational behavior.														
3) Security prices move in trends that persist over long periods.														
4) While the causes of changes in supply and demand are difficult to determine, the actual shifts in supply and demand can be observed in market price behavior.														
														
The major challenge to technical analysis is the efficient market hypothesis (EMH).														
														
Fundemantalists believe they  can forecast value changes by analyzing earnings and other publicly available data. 														
Fundamentalists belive prices adjust quickly.														
EMH advocates believe the price adjustment to new information happens almost instantaneously.														
Fundamentalists, through their research, look for changes in the basis of value, which eventually leads to change in the supply and demand for the stock.														
Technicians look for evidence of changes in supply and demand through market signals and indicators.														
