---
title: 'CFA Level 1 - Economics'
date: '`r Sys.Date()`'
slug: cfa-level-1-economics
categories: 
- CFA Level 1
tags:
- Economics
mathjax: true
thumbnail: ""
lead: "" #"Example lead - highlighted near the title" # Lead text
comments: false # Enable Disqus comments for specific page
output:
      blogdown::html_page:
            toc: true
summary: "The CFA level 1 exam covers economics in great detail, specifically, macroeconomics. It covers demand and supply, market structures, and more."
---

## Supply and Demand   

### Determinants of Demand								
* Income									
* Tastes and preferrences		
* Prices of related goods
* Expectations
* Number of buyers
									
### Determinants of Supply									
* Prices of input goods	
* Technology
* Productivity
* Expectations of producers
* Number of producers in the market
* Prices of related goods									

## Price Elasticity									

### Price Elasticity of Demand									
* $\mathrm {\large {E_{p} = \frac{\text{%}\Delta \text{Quantity demanded}} {\text{%}\Delta Price} = \frac{\Delta Q_{d} \div Q_{ave}} {\Delta P \div {P_{ave}}}}}$
* Concerned with absolute value					

## Factors that influence Elasticity of Demand							
* Current price
* Closeness and number of substitutes					* Proportion of income spent on the goods
* Time elapsed since price change (search for substitutes)

### Cross Elasticity of Demand

* $\mathrm {\large {E_{c} = \frac{\text{%}\Delta \text{Quantity demanded}} {\text{%} \Delta \text{Price of substitute or complement}}}}$
* Value is positive for a substitute
* Value is negative for a complement										

### Income Elasticity of Demand

* $\mathrm {\large {E_{i} = \frac{\text{%}\Delta \text{Quantity Demanded}} {\text{%} \Delta Income}}}$

* Value is greater than 1 (normal good, income elastic)
* Value is between 0 and 1 (normal good, income inelastic)
* Value is negative (inferior good)										
									
### Price Elasticity of Supply

* $\mathrm {\large {E_{p} = \frac{\text{%}\Delta \text{Quantity Supplied}} {\text{%} \Delta Price} = \frac{\Delta Q_{s} \div Q_{ave}} {\Delta P \div {P_{ave}}}}}$
* Concerned with absolute value					

### Factors that influence Elasticity of Supply

* Resource substitution possibilities				
* Time frame for the supply decision
* Time Frames of Supply
      1. Momentary supply curve
            * Shows the response of the quantity supplied immediately following a price change
      2. Long-run supply (LRS)	
            * Shows the response of the quantity supplied to a change in price after all the technologically possbiel ways of adjusting supply have been exploited.
      3. Short-run supply (SRS)
            * Shows how the quantity supplied responds to a price change wen only some of the technologically possible adjustemnt s to production have been made.												

## Macro Economy

### Gross Domestic Product (GDP)								
* GDP = C + I + G + EX							
* GDP equals the value of the total goods and services produced within a country over a given period of time			
* GDP can be measured in current or inflation-adjusted (constant) prices (real GDP)
* Taxing for government spending stifles private investment and consumption
* EX - consider what countries trading with			
* The structure of the domestic production of goods and services determines the growth of production						* Antitrust Legislation							
								
### Causes of inflation							

* A greater volume of money chasing the same quantity of goods
* The same quantity of money circulating with greater velocity							
								
Efficiency occurs when consumer and producer surplus is maximized								
								
### Tax incidence								

* The division of the burden of a tax between the buyer and the seller
* The elasticity of demand and supply determine the structure of tax sharing by buyers and sellers.
* Low elasticity of demand (inelastic) causes taxes to be easily passed onto buyers
* High elasticity of demand (elastic) causes taxes to rejected by buyers				* If supply is perfectly inelastic, the burden of the tax is borned entirely by the supplier.	
* If the supply of a factor of production is perfectly elastic, the burden of the tax is borne entirely by the consumer.
* If the supply (of a factor of production) is not perfectly inelastic, at least part of the tax is borned by the buyer.								
								
Taxing economic rent is efficient.								
								
### Opportunity Cost								
* The value of the highest-valued alternative forgone

### Economic Profit

* The profit earned after deducting explicit and implicit opportunity costs								
								
### Implicit Costs (opportunity costs):

* Implicit rental rate - (1) economic depreciation and (2) foregone interest
* Normal profit - what owner could have earned in next highest paying activity
      + e.g. foregone wages, foregone interest, economic depreciation, normal profit								
								
### Economic Efficiency								
* Output relative to input cost		
* The cost curves are determined by a firm's technology		
								
### Short-Run Output	

* Labor is the only variable factor of production in the short-run

### Average Total Cost (ATC) is U-shaped								
* Marginal Cost (MC) intersects Average Total Cost at the minimum ATC point							

## Long-Run Output

* All factors of production are variable			
* The long-run ATC is a culmination of all possible ATC curve's for varying mixes for factors of production
								
### Factors that contribute to output (GDP)

* Labor								
* Capital inputs								
* Natural resources							
* Entrepreneurial talent						
* Technology								

										
### Perfect Competition												
1. Many firms and identical products
2. No barriers to entry
3. Established firms have no advantage over new firms
4. Sellers and Buyers are well informed about prices												
* Perfect competition arises if the minimum efficient scale of a single producer is small relative to the demand for the good service (many companies - low economies of scale)	
* ***Price Taker:***
  + Marginal Revenue (MR) = Price (Marginal Revenue curve = Demand curve)			
* A firm's goal is to maximize economic profit.  Economic Profit = Total Revenue - Total Cost (includes opportunity cost of production, including normal profit of entrepreneur)
* In the short run, a firm cannot avoid incurring its fixed cost (sunk cost), but the firm can avoid variable costs by temporarily laying off its workers and shutting down.						

### Shutdown Price 												
* Price that just covers a firm's total variable cost.

### Firm's Supply Curve

* At prices that exceed minimum average variable cost, the supply curve is the same as the marginal cost curve above the shutdown point.			
* At prices below minimum average variable cost, the firm shuts down and produces nothing.
* In the short run, a firm's fixed costs are sunk costs, so the variable costs are the only relevant costs.				
										
### Monopoly												
* The firm's demand curve is the market demand curve
* A monopoly produces below the efficient level (excess capacity)
* A monopoly charges a price above the efficient level (markup)

### Labor Unions								

* Unions compete with non-union workers
* Unions try to restrict entry into the field by setting limits and tests that potential workers must pass to enter the union (and possibly field)
* Unions try to restrict employment below the competitive level hoping to expand employment opportunities for their members
* A minimum wage rate is usually a price floor that creates a surplus of labor (more unemployment)												
										