---
title: "CFA Level 2: Alternative Investments (part 1)"
slug: cfa-level-2-alternative-investments-part-1
description: ""
lastmod: "`r Sys.time()`"
categories:
- CFA Level 2
tags:
- Alternative Investments
output:
      blogdown::html_page:
            toc: true
summary: "Alternative investments cover real estate, commodities, hedge funds, private equity, and more. Each of these has its own unique risk and reward features."
thumbnail: "/post/cfa-level-2-alternative-investments-part-1_files/barley.jpg"
---


## Income Property Analysis and Appraisal	
			
### Capitalization Rate	

* Cap rate = rNOI - gNOI												
												
### Measuring the Cap Rate	

1. Market Extraction Method (ME)					
2. Band-of-Investment Method (BOI)					
3. Built-Up Method (BU)								

												
3.) Built-Up Method (BU)												
* The built-up method depends on macroeconomic factors, and is generally used when comparables are not present. The built-up method doesn't consider the method of financing.												
												
												
C0 = pure rate + liquidity premium + recapture premium + risk premium.												
												
												
												
2.) Band-of-Invesment Method (BOI)												
The BOI utilizes a WACC as an estimate of the market capitalization rate. It is appropriate for properties that utilize both debt and equity financing. In the BOI method, we adjust the capitalization rate by adding a sinking fund factor.


Sinking Fund Factor

SFF = PMT(i/12, n*12, PV = 0, FV = -1)

Annual Mortgage Cost = annual YTM + SFF (%)												
												
C0 = WACC = (mortgage weight x mortgage cost) + (equity weight x equity cost).												
												
												
Equity Reversion After Taxes (ERAT)												
												
	Net selling price											
	- Mortgage balance											
	- Taxes											
	= ERAT											
												
## Recaptured Depreciation	

* Recaptured depreciation represents  depreciation that was taken in anticipation of a decline in the value of an asset that ultimately did not materialize.
* Recaptured depreciation = Accumulated depreciation (A/D)
* Tax on recaptured depreciation = Accumulated depreciaiton * tax on recaptured depreciation												
Tax on capital gains = tax rate on capital gains * (capital gain - recaptured depreciation)												
												
												
## Private Equity Valuation	
												
Definitions												
Portfolio Company - companies that private equity firms invest in												
Private Equity Firm - companies that create portfolios of portfolio companies and allow PE investors to invest in												
Private Equity Investor - outside investors who makes an investment in a fund offered by the PE firm												
												
### Unique Sources of Value for Private Equity Investments  

1. Ability to re-engineer the firm for efficiency
2. Ability to acquire debt at favorable terms
3. Superior alignment of interests between managers and owners

#### Definitions	

* Compensation - payment that is closely linked to the firm's performance	
* Tag-Along, Drag-Along Clauses - the requirement that an acquiring firm extend the acquisition offer  to all shareholders, including firm management
* Board Representation - The private equity firm is ensured control through board representation in a major event												
Noncompete Clauses - Company founders must sign a clause that prevents them from competing against the firm withina  prespecified period of time												
												
Priority in Claims - Private equity firms receive their distributions before other owners												
Required Approvals - Changes of strategic importance must be approved by the private equity firm												
Earn-Outs - These tie the acquisition price paid by the private equity firm to the portfolio company's future performance over a specified time period.	
								
		
## Adjustments for Probability of Failure	

1. If the probability of failure in any given year is expected to remain constant, use...

$\mathrm {\large {r_{adj} =  \frac{1 + r_{unadj}} {1 - Pr(failure)} - 1}}$
		
2. If the probability of failure in any given year is expected to change each year, adjust each year's expected cash flows to reflect the Probability of failure ($0 cash flow, Pr(failure)) or adjust the expected exit value.
				
## The Basic Venture Capital Method		

* Step 1: Determine the post-money valuation ("POST")
										
      * $\mathrm {\large {POST =  \frac{\text{Exit Value}} {(1 + r)^t}}}$
      * The only positive cash flow (capital gain, no dividends) in this model occurs at the time of exit (typically an IPO or acquisition)
      * The Exit Value is an estimate of the value of a company at the time of an exit event, be it an IPO or an acquisition
      * $\mathrm {\large {\text {Exit Value} = \text{Earnings Multiple} \times \text{Estimate of terminal earnings}}}$
      * $\mathrm {\large {\text {Exit Value} = \text{PV(expected future cash flows)}}}$
      * Exit Value measures the value of the company in the case of _success_

* Step 2: Determine the pre-money valuation ("PRE")

      * $\mathrm {\large {\text {PRE} = \text{POST - Investment}}}$

* Step 3: Determine the ownership fraction for the investor (f)
    + $\mathrm {\large {f =  \frac{\text{Investment}} {POST}}}$
* Step 4: Determine the number of investor shares ("y")
* Step 5: Determine the price per share										
												
								
									
## Investing in Commodities	
												
Commodity Futures Trading Commission (CFTC)												
U.S. regulator of futures trading												
												
Long-only investment in commodities is usually obtained via collateralized long positions in commodity futures, forwards, or swaps.												
												
Contango			Normal Contango									
Futures price > Spot price			Futures price > E(Spot price)									
												
Backwardation			Normal Backwardation									
Spot price > Futures price			E(Spot price) > Futures price									
												
												
## Commodity Futures Returns	 

1. Collateral yield - the return on cash used as margin to take long derivatives exposure				
2. Roll yield - the return from rolling forward the maturity of the derivatives position by closing out a current position and entering a new contract.
      * The long position experiences positive roll yields when markets are in backwardation; the long investor can buy the the commodity below the current spot price from a hedger.
3. Spot yield - the return on the spot asset

## Commodity prices decline for the following reasons (shifts in demand/supply): 	

1. Introduction of new supplies and new production technology
2. Subsitutiton of one commodity for another when prices rise	3. Reduction in the use of certain commodities in technological processes

## Supply and Demand	

* Most of the fluctuation in commodity prices comes from changes in demand. Changes in supply are usually smaller and slower to respond.

Today's commodities market is no longer dominated by hedgers and natural backwardation and can move towards backwardation or contango.

At the maturity date of the futures contract, the investor can either take physical delivery of the commodity or roll the futures contract, which means buying another contract with a  new maturity date.

The risk-return profile of commmodities over the past 25 years is similar to that of U.S. equities.

Commodities tend to have a negative correlation with equities and therefore provide some diversification benefits.

Portfolio optimization techniques suggest that portfolios should contain about 15-25% of commodities.

## Performance of Hedge Funds

### Maximum Drawdown	

* The largest percentage decrease in investment value from peak to valley that has ever occurred for a fund within a specified time period.

### Measures left-tail risk	

#### Value at Risk (VAR)		

* The minimum loss that would be expected over a period of time as well as the probability of occurrence	
* Assumes hedge fund returns are normally distributed (uses zstat and p-value)
* Assumes that component risks are additive

### Other Risk Measures	

1. Loss Standard Deviation - standard deviation that focuses on the left side of the return distribution
2. Downside Deviation - similar to loss standard deviation, but specifies a minimum acceptable return (used in the Sortino Ratio)

## Hedge Fund Risks           

1. Fraud Risk			
2. Operational Risk				
3. Investment Risk							

## Maximum Drawdown	

* A measure of the largest loss that can be experienced.

## Value At Risk		

* A measure of the largest loss that can be experienced AND the associated probability of the loss event					* Assumes hedge fund returns are normally distributed	
* Assumes hedge fund risks are additive												
												
