---
title: 'CFA Level 2: Fixed Income (part 1)'
author: ''
lastmod: '`r Sys.time()`'
slug: cfa-level-2-fixed-income-part-1
categories: 
- CFA Level 2
tags: 
- Fixed income
output:
      blogdown::html_page:
            toc: true
summary: 'Fixed income covers the topic of bonds and other coupon-like investment securities.'
thumbnail: '/post/2020-07-30-cfa-level-2-fixed-income-part-1_files/calculator.jpg'
---


## Credit Analysis

### Credit Risk	

1. Default Risk	
2. Credit Spread Risk
3. Downgrade Risk

* Credit ratings by the nationally recognized rating agencies assess __default__ risk only.

### Releases by Rating Agencies           

* Credit Rating - reflects the probability of default (short- and long-term debt) and the rate of loss (long-term debt)
* Rating Watch - announcement that the rating agency is reviewing a particular issue in advance of a potential rating change

Rating Outlook - 

* Total Debt = Current Liabilities + Long-Term Debt

### High-Yield Issuers         

1. Bank debt
      + Loans acquired from banks
2. Reset notes
      + Bonds whose coupon rates are adjusted periodically
3. Senior and Subordinated debt						
* High-yield borrowers typically rely on short-term, floating-rate, senior bank debt.
* "Senior Bank Debt" has a higher claim on assets than "Senior Debt."

## Liquidity
				
### Liquidity Factors		

1. Money Supply (traditional guage of liquidity)
2. Appetite for Risk							

Traditional Banks (Commercial Banks)												
* Heavily regulated
* In return for regulation, banks receive (1) deposit insurance (FDIC) and (2) access to the Fed's discount window (guaranteed source of liquidity)

### Shadow Banking System	

* The group of non-bank institutions that offer liquidity to the market
* The commercial bank's most important economic role is to accept funds from depositors and lend those funds to borrowers.
* Shadow banks raise money from individual investors and provide it directly or indirectly to firms and households, a function that was once exclusively the domain of commercial banks.
* Examples of Shadow Banks					
      + Hedge funds
      + Private Equity Funds
      + Trading houses
      + Conduits
      + Structured investments
      + REITs
      + Collateralized debt obligations (CDOs)
      + Collateralized loan obligations (CLOs)												
								
### Funding Sources of the Shadow Banking System

1. Reverse repos			
2. Asset-backed Commercial Paper

### Minsky Framework	

1. Hedge Unit (borrower can afford interest and principal payments)

2. Speculative Unit (borrower can afford interest payments only)
3. Ponzi Unit (borrower can't afford interest or principal payments)

* In 2006, mortgage lenders were effectively granting at-the-money call options on the value of their properties. 

## Term Structure and Volatility of Interest Rates	
										
* Yield Curve Shifts
      1. Parallel shifts
      2. Nonparallel shifts: Twists
            + Flattening of  curve (lower slope)
            + Steepening of curve (higher slope)
      3. Nonparallel shifts: Butterfly
            + Positive butterfly shift (less curvature)
            + Negative butterfly shift (more curvature)												
												
Factors Contributing to the Returns on Zero-Coupon Treasury Securities												
1.) Parallel shifts in yield curve (90%)												
2.) Twists, change in yield curve slope (8.5%)												
3.) Butterfly shifts, changes in curvature of yield curve (1.5%)												
												
Yields for Yield Curve												
1.) Treasury Coupon Strips												
2.) On-the-run Treasury issues												
3.) On-the-run Treasury issues and selected off-the-run Treasury issues												
4.) All Treasury coupon securities and bills												
												
The liquidity of the strips market is not as great as that of the Treasury coupon market.												
												
A problem with just using on-the-run issues is the large gap between maturities, especially after 5 years.												
												
Swap Curve (LIBOR curve)												
												
												
												
Advantages of Using the Swap Curve												
												
												
												
												
Pure Expectations Theory of the Term Structure of Interest Rates												
												
												
												
												
												
												
												
												
												
Liquidity Preference Theory of the Term Structure of Interest Rates												
												
												
												
												
												
Preferred Habitat Theory of the Term Structure of Interest Rates												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
Valuing Bonds with Embedded Options												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
Mortgage-Backed Sector of the Bond Market												
												
Agency Passthrough Securities issued in U.S.												
1.) Ginnie Mae - Issued by the Government National Mortgage Association (GNMA) and possess no credit risk												
2.) Freddie Mac - Issued by the Federal Home Loan Mortgage Corporation (FHLMC)												
3.) Fannie Mae - Issued by the Federal National Mortgage Association (FNMA)												
												
The most important characteristic of passthrough securities is their prepayment speed.												
												
Factors Affecting Prepayment Speeds												
1.) Prevailing mortage rates												
2.) Housing Turnover (interest rate path)												
3.) Characteristics of the underlying mortgages												
												
Single Monthly Mortality Rate (SMM)												
												
												
												
												
												
												
CMBS typically have some form of loan-level prepayment protection, while residential MBS do not.												
CMBS mortgages are structured as non-recourse.												
												
Mortgage-backed securities, which triggered the financial collapse, were priced using the Gaussian copula model.												
												
Mortgage-Backed Securities (MBSs)												
Securities that are secured by pools of mortgage loans that provide collateral and cash flow backing												
Examples: mortgage passthrough securities, collateralized mortgage obligations, stripped mortgage-backed securities												
												
Some GSE's; namely, Ginnie Mae, Fannie Mae, and Freddie Mac; purchase mortgages from private lenders to provide funds, that would not otherwise be provided privately, for mortgage loans.												
												
												
Mortgage Securitization 												
Process of combining similar debt obligations as collateral for new securities												
Increases the debt's attractiveness to investors												
Increases the availability of funds for home mortgages												
												
Mortgage Pass-through Security												
Passes the payments made on a pool of mortgages through proportionally to each security holder												
												
Collateralized Mortgage Obligations (CMOs)												
??? Securities derived by reallocating the cash flows from mortgage-backed securities or pools of mortgage loans in order to create multiple classes, or tranches, of securities with coupon rates and average lives that differ from the underlying collateral as  a whole												
??? Although CMO tranches can be structured (through the use of cash flow priority and "support" tranches) to give somewhat more predictable cash flows, the actual future cash flow and hence value of CMOs are subject to change												
??? Securities with specific rights that vary from that of MBSs (do not simply pass through a cash flow proportional to the percentage of ownership)												
												
??? Feature multiple "tranches" that feature varying risks and expected cash flows												
??? Permit the "redistribution of prepayment risk"												
??? Permits the "creation of securities with various maturity ranges"												
??? Created to appeal to a wider group of investors so that borrowing costs decline.												
??? A CMO is an alternative to mortgage loans and conventional mortgage-backed securities												
												
Stripped MBSs												
Either the principal-only (PO) or interest-only (IO) portions of a mortgage passthrough security												
												
Planned Amortization Class (PAC)												
A type of tranche that is characterized by a nearly fixed amortization schedule.  It is designed to not be subject to prepayment risk.												
												
Some underlying mortgages are insured by the government, providing a credit guarantee in the case of borrower default, but does not provide insurance to tranche investors against changes in interest rates and subsequent prepayments.												
												
												
A major flaw in mortgage-backed security pricing was the underestimation of the correlation among residential assets. Few priced the securities to account for a potential cascading effect.												
												
Benefits of Structured (Securitized) Assets												
1.) Risk Transfer												
2.) Liquidity												
												
A securitization is a self-liquidating aset pool that generates cash to repay the bonds that finance the assets' purchase from the bank that originated them.												
												
Structured Investment Vehicles (SIVs)												
												
												
												
Asset-Backed Sector of the Bond Market												
												
Asset-Backed Securities												
												
												
Credit Enhancements												
External:												
1.) Letters of Credit												
2.) Corporate Guarantees												
3.) Bond Insurance												
												
												
Internal:												
1.) Reserve Funds												
2.) Senior/Subordinated Structure												
3.) Over-collateralization												
4.) Excess servicing spread accounts												
												
Prepayment tranching is also referred to as time tranching. Prepayment tranching refers to when an asset or mortgage backed security is subdivided so some components are exposed to more prepayment risk than others. 												
												
												
In an asset-backed security backed by non-amortizing assets (e.g. credit cards), the composition of loans in the pool will change. During the lockout period, principal payments are not distributed to bondholders. Instead, new loans are purchased and this structure is referred to as a revolving structure. However, the retirement of principal (i.e. a call provision) in a revolving structure can be triggered by several different events. These events include a specific date, when the collateral falls below a certain level, or when cumulative losses in the collateral reach a certain level. 												
												
												
												
												
												
In an asset-backed security backed by amortizing assets (e.g. automobile loans), the composition of loans in the pool will not change. No new loans are purchased. A lockout period provision refers to an ABS backed by non-amortizing loans.												
												
												
												
												
Countries with efficient legal systems and common-law origin are more likely to have more long-term debt issues by low D/E ratio issuers.												
												
												
Fannie Mae and Freddie Mac												
Congress created Fannie Mae and Freddie Mac to provide liquidity in the mortgage market by allowing these government sponsored enterprises to buy mortgage loans in the secondary market.												
												
												
In essence, FNMA and FHLMC subsidize the bulk of U.S. mortgages.												
FNMA and FHLMC have been the high priests of the religion of home-ownership.												
												
In 2008 the U.S. government took direct control of FNMA and FHLMC amid a housing price spiral and soaring mortgage defaults.												
												
Institutional Loans												
Loans mostly funded by investors instead of banks												
												
Covered Bonds												
Structured security that is backed by the repayments on a pool of loans, but unlike most asset-backed securities, covered bonds remain ona banks books and stands as a backer to the bonds												
												
Collateralized Debt Obligations (CDOs)												
Structured assets that invest in leveraged loans, high-yield bonds and other asset-backed securities.												
Sliced into tranches carrying different risks which were sold to investors as bonds or equity.												
												
Synthetic Collateralized Debt Obligations												
A set of repackaged credit default swaps (protection against default on debt, rather than cash or loans)												
Gives ivnestors exposure to the credit markets without having to buy the underlying assets												
												
Risk Factors for Structured Securities												
1.) Prepayment rates												
2.) Default rates												
3.) Loss severity												
												
												
												
												
												
												
Valuing Mortgage-Backed and Asset-Backed Securities												
												
Cash Flow Yield												
The yield that equates the present value of a security with its market value and accrued interest (i.e. IRR for MBSs and ABSs)												
												
To determine a cash flow yield, some assumption about the prepayment rate must be made.												
												
The cash flow for MBS and ABSs is usually monthly.												
												
Bond-Equivalent Yield (for MBSs and ABSs)												
BEY = 2*[(1+im)6-1]												
												
Yield Spreads												
1.) Nominal spread												
2.) Zero-Volatility Spread												
3.) Option-Adjusted Spread												
												
A trial-and-error procedure is required to determine the zero-volatility spread.												
												
Interest Rate Path-Dependency												
Prepayments (cash flows) are sometimes dependent on the path of interest rates, instead of just the current level of interest rate.  Not all outstanding mortgages are underwritten at the current interest rate level; some were refinanced when interest rates were even lower than they appear today and there is little incentive to refinance, or prepay, today.												
												
												
												
Monte Carlo Simulation												
Step 1:												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
Asset-Backed Sector of the Bond Market												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
Asset-Backed Sector of the Bond Market												




<hr>

<a id="nav__prev" href="../cfa-study-topics">Topics List</a>

<a id="nav__next" href="../cfa-level-1-fixed-income-part-2">Next</a>

<br>

