---
title: "CFA Level 1: Ethical and Professional Standards"
author: ''
date: "`r Sys.Date()`"
slug: cfa-level-1-ethical-and-professional-standards
categories:
- Ethical and Professional Standards
tags:
- CFA Level 1
output:
      blogdown::html_page:
            toc: true
summary: "Ethics is a commonly failed topic in the CFA exams. It can be quite tricky, so it is critical to thoroughly understand the topic. We hope our notes help you grasp the main points."
thumbnail: ''
---


## Professional Conduct Program (PCP)					
* If a Designated Officer determines that a sanction against a member is warranted, the member must either accept the sanction or face a hearing by a panel of CFA Institute members.
* Members who provide confidential information that is solicited by  PCP staff is not in violation of the Standard III(E) Preservation of Confidentiality.

## Disciplinary Review Committee (DRC)

* The DRC is responsible for the enforcement of the CFA Institute Code of Ethics and Standards of Practice in an effort to maintain the integrity of CFA Institute membership and the CFA designation.								
										
## Primary Principles of CFA Institute Bylaws and Rules of Procedure

1. Fair Process					
2. Confidentiality of proceedings

## Code of Ethics		

1. Act with Integrity, Competence, Diligence, and Respect with all affected parties						
2. Place the integrity of the profession and interest of clients above personal interest	
3. Use Reasonable care when giving advice, taking advice, and conducting investment analysis				
4. Practice and encourage others to practice in a professional and ethical manner that will promote the profession		
5. Promote the integrity of, and uphold the rules governing, capital markets
6. Maintain and improve professional competence

## Standards of Professional Conduct	

i. Professionalism						
ii. Integrity of Capital Markets					
iii. Duties to Clients	
iv. Duties to Employers						
v. Investment Analysis, Recommendations, Actions
vi. Conflicts of Interest
vii. Responsibilities as a CFA Instute Member or CFA Candidate

## Professional Standards	

i. Professionalism
      a. Knowledge of the Law
            + Reporting Violations:					
	            1. Inform employer's compliance department and supervisor and attempt to remedy the solution
	            2. Dissociate from activity (Resignation or reassignment)
	            3. Inform legal or regulatory authorities
            + Must comply with the more strict law, rule, or regulation
            + Must not knowingly participate or assist in and, must dissociate from any violation of such laws, rules, or regulations
            + Members or Candidates are can participate in a violation simply by having knowledge of the violation and not taking action to stop it
            + Ignorance of a rule or law is not a sufficient defense
            + Don't have to report violations of laws or the Code and Standards to either the CFA Instute or governmental authorities, unless required by law					
            + Must disassociate from any illegal activity and actively urge the firm (either an immediate supervisor or a compliance officer) to cease any conduct that violates the law or an applicable regulation or standard. Inaction might be judged, (even in a court of law), as participating or assisting, which violates the Standard.
      b. Independence and Objectivity
            + Must use reasonable care and judgment to achieve and maintain independence and objectivity
            + Must not offer, solicit, or accept any gift, benefit, compensation, or consideration that reasonably could be expected to compromise their own or another's independence and objectivity
            + Gifts must be disclosed to the member's employer in any case, either prior acceptace, if possible, or subsequently.
            + No requirement to notify "all related parties," because it is the obligation of the employer to determine if loyalties to other clients will be affected. After permission is received from employer, receipt of gift is acceptable.
            + Gifts that are offered to demonstrate a firm's product/service are acceptable and need not be disclosed
            + Must act as an independent source of financial incite, not reliant on other professionals for decisionmaking
            + Must not accept gifts that are hard to come by and most likely expensive since they pose a potential threat to objectivity
            + Gifts that are accepted for prior performance and not contingent on future performance don't threaten objectivity
            + Gifts that are contingent on future performance must be authorized by a supervisor or compliance department
            + Gifts of significant value can be accepted as long as an employer authorizes acceptance AND the gifts will not threaten duty to other clients
            + Gifts that are a part of the required itiniery and not easily substitutable (such as special flights) can be accepted
            + Reasonable payment for hotel rooms and chartered flights is acceptable.  Irrelevent or lavish hospitality could compromise objectivity and should be avoided.
            + Gifts that are given to inspire high performance are allowable, but if it is contingent on future performance, employer consent is required by supervisor or compliance department
            + Must not participate in oversubscribed IPOs
            + When providing analysis of a security AND maintaining ownership of the security, whether self-managed or not, member must disclose the ownership to appropriate clients.
            + Members may accept modest gifts, which it specifically defines as being anything worth less than US$100, as long as they do not affect objectivity.
            + Be sure there are effective "firewalls" between research/investment managemetn and investment banking activities
            + Do not confine research to discussions with company management; use several sources
      c. Misrepresentation
            + Must not knowingly make any misrepresentations relating to professional activities
            + All sources in an analyst's report must be documented - except factual information published by recognized financial and statistical reporting services
      d. Misconduct
            + Must not engage in any professional conduct involving dishonesty, fraud, or deceit or commit any act that reflects adversely on professional reputation, integrity, or competence
            + Standard I(D) Misconduct primarily covers professional activities but also refers to any activities (professional or personal) that reflect adversely on members' professional competence, integrity, or reputation.
            + Must not use CFA Instute's Professional Conduct Program to settle personal, political, or other disputes not related to professional ethics
            
ii. Integrity of Capital Markets
      a. Material Nonpublic Information
            + Must not act or cause others to act on material nonpublic information (information that would likely have an impact on the price of a security or that reasonable investors would want to know before making an investment decision)
	      + Must make good-faith effort to prevent the transfer and misuse of material nonpublic information
	      + Disclosure in widely-used news sources would likely cause traders to act
	      + __Mosaic Theory__: nonmaterial, nonpublic information combined with research can be used to make investment decisions and recommendations
	      + An analyst conference call is not public disclosure.
	      + Information is nonpublic until it has been made available to the marketplace
	      + Recommended to restrict proprietary trading, but still make unsolicited trades
	      + Should provide an information firewall to limit transmittal of material nonpublic information within firm
            + Common knowledge is regarded as "public" information
            + Should first make reasonable efforts to achieve public dissemination and then, if necessary, disclose information only to designated supervisory and compliance personnel.
	      + A firm's internal information "firewall" should include a reporting system in which authorized personnel review and approve interdepartmental communications.
      b. Market Manipulation						
	      + Must not engage in practices that distort prices or artificially inflate trading volume with the intent to mislead market participants		
	+ Must not spread false information
	+ Whatever the motivation, the intent must not be to deceive market participants
iii. Duties to Clients
      a. Loyalty, Prudence, and Care
            + Have a duty of loyalty, act with reasonable care, and exercise prudent judgment
            + Must act for the clients' interests and place their interests before their employer's and own self-interest
            + Make investment decisions in the context of the entire portfolio
            + Allowed to make preparations for future employment while still employed, as long as it doesn't affect loyalty to current employer
            + Soft dollar commissions must be used to benefit the client
            + Voting on proxies is only required for nonroutine issues with material impact
            + Client brokerage commissions must not be directed to pay for the investment manager's operating expenses.
      b. Fair Dealing
            + Must deal fairly and objectively when providing investment services
            + Must fairly disseminate investment information (to all clients) and trade for clients' accounts first
            + May accept unsolicited trade requests after notifying (verbal or written) a client of changes in recommendations before processing trades
            + Can offer different levels of service to clients, but must disclose this to all clients
            + Must provide reasonably sufficient time for clients to trade before making personal trades
            + Recommended to limit the number of people who know about changes to recommendations
            + Should forgo any sales to themselves or their immediate families to free up additional shares of oversubscribed stock issues for clients
            + Employers should compare personal transactions of employees with those of clients on a regular basis regardless of the existence of a requirement by any regulatory organization.
      c. Suitability
            + Must make reasonable inquiry into a client's investment experience, objectives and constraints, and regularly update this information													
	Suitability is judged in an overall portfolio context and not on a security-by-security basis													
	Make sure investment recommendations conicide with clients' written objectives													
	Brief communications are permitted (as brief as a list of recommended securities) as long as these recommendations are supported by appropriate background reports that can be made available to clients upon request. Sending a recommended list to all clients, even though not every recommended security is suitable for them, is not a violation of the Standards.													
														
														
	For unsolicited trades that conflict with investment objectives, must receive affirmative statement acknowledging that suitability is not a concern													
														
	Must updated Investment Policy Statement (IPS) at least annually													
	Suitability does not become a concern until an investor has taken action													
	For unsolicited trades that conflict with investment recommendations, must advise the client of the change in recommendation before accepting the order													
														
														
III(D) - Performance Presentation														
	Must make reasonable efforts to ensure that performance presentation is fair, accurate, and complete													
	Must include terminated accounts as part of historical performance													
	Consider the sophistication of audience													
	No minimum performance history is required													
	Simulated results can be reported, as long as this is disclosed													
	Must disclose if results are realized under the authority of another firm													
	Footnote disclosure is not enough to comply with this standard													
	Recommended to disseminate  new recommendations to all clients who express an interest or for whom the investment is suitable													
	Must cite specific source of investment performance (e.g. "investment experts" is too vague)													
	Recommended to use GIPS in performance presentation													
														
III(E) - Preservation of Confidentiality														
	Must keep client information confidential unless 1.) it involves illegal activities, 2.) disclosure is required by law, or 3.) the client permits disclosure													
														
	Must report illegal activity to employer first and then, if necessary, seek outside counsel													
	Can disclose confidential information to authorized fellow employees to ensure that a manager is aware of a client's needs and concerns													
														
	Must not disclose confidential infortion, even if it benefits the client													
														
IV: Duties to Employers														
IV(A) - Loyalty														
	In matters of employment, must act for the benefit of their employer and not deprive their employer of advantage of their skills and abilities													
														
	May use prior knowledge and professional skill in new jobs													
	Must not misappropriate trade secrets or solicit employer's clients before leaving, unless written consent from employer is received													
	No requirement to place employer interests above family and other personal obligations													
	Whistleblowing is not a violation of the Standards, unless it is done to promote personal gains instead of to protect clients or markets													
	Both employees and independent contractors must abide by the Standards													
														
IV(B) - Additional Compensation Arrangements														
	Must not engage in activities that might reasonably create a conflict of interest with an employer, unless written request and consent from all parties is obtained													
														
	Independent practice for compensation is allowed if a written notification is provided to the employer fully describing all aspects of the services, including compensation, duration, and the nature of the activities and if the employer consents to all terms of the proposed independent practice before it begins													
														
														
	Accepting work that competes with employer is acceptable, but only after written notification is received from employer													
														
														
IV(C) - Responsibilities of Supervisors														
	Must make reasonable efforts to detect and prevent violations of applicable laws, rules, regulations, and the Code and Standards by anyone subject to supervision or authority													
														
	Must take action to prevent future violations													
	Must incorporate and disseminate details of a Professional Conduct Evaluation to all appropriate employees													
	If a member cannot discharge compliance responsibilities because of a poor compliance system, the member should decline in writing to accept supervisory responsibility until the firm adopts an adequate system													
														
														
V: Investment Analysis, Recommendations, and Action														
V(A) - Diligence and Reasonable Basis														
	Must exercise diligence, independence, and thoroughness in all investment activity													
	Must have a reasonable and adequate basis for investment actions													
	Use of an unfamiliar investment model is not a violation, unless there is a reasonable suspicion of inadequacy													
	When using third-party analysis, must review assumptions used and evaluate the objectivity and independence of recommendations													
														
	Opinon of another analyst is not an reasonable basis for a recommendation													
														
V(B) - Communication with Clients and Prospective Clients														
	Must disclose to clients the basic format and general principles of the investment processes													
	Must promptly disclose changes to the basic format and general principles													
	Must distinguish between fact and opinion													
	Must notify (verbal or written) of material changes in investment strategy and methods													
	Personal bankruptcy does not compromise professional reputation, so it is not a required disclosure													
	Must disclose general strategy of investment management; trade details need not be disclosed													
														
      c. Record Retention
            + Must develop and maintain appropriate records to support investment-related actions and communication with clients and prospective clients
            + CFA Institute recommends 7 years of record retention
            + The firm is generally responsible for record-keeping													
														
vi. Conflicts of Interest
      a. Disclosure of Conflicts
            + Must make full and fair disclosure of matters that could reasonably be expected to impair their independence and objectivity or interfere with respective duties to clients, prospective clients, and employers
            + Must ensure that disclosures are prominent and delivered in plain language, and communicate the relevent information effectively
            + Ownership of an analyzed stock is not a violation, but significant ownership could reasonably be expected to impair judgment
            + Best practice is to disclose ownership of a covered stock to the employer and in the investment report
      b. Priority of Transactions
            + Investment transactions for clients and employers must take precedence over personal trades for personal benefit
            + Must not trade shares (client or personal shares) before issuing a recommendation report
	      + Recommended to avoid participating in IPOs to avoid the appearance of conflict													
	Disclosure is not enough to comply with this standard and the execution price is not relevant
      c. Referral Fees
            + Must disclose appropriately to employer, clients, and prospective clients, as appropriate, any compensation received from (or paid to) others for the recommendation of products or services
            + Must disclose referral agreements, whether external or internal 
            + Referral fees that are commonly present and reasonably expected to be paid by employer to employee need not be disclosed
vii. Responsibilities as a CFA Institute Member or CFA Candidate														
VII(A) - Conduct as Members and Candidates in the CFA program														
	Must not engage in any conduct that compromises the reputation or integrity of CFA Institute or the CFA designation or the integrity, validity, or security of the CFA examinations													
														
	Preparation of an attempt to violate the integrity of an exam challenges the integrity of the CFA program, even if the action is not carried out													
														
														
VII(B) - Reference to CFA Institute, the CFA designation, and the CFA program														
	Must not exaggerate the meaning of the CFA designation or suggest it's membership gives analysts superior performance potential													
														
	Must not use "CFA" as a noun													
	To Be considered a candidate, individuals must be registered to take the next schedule CFA exam													
	Allowed to express negative opinions about the CFA Institute of CFA program													
	Use of the CFA designation to those who have passed all three levels of the CFA Program, have received their charters, and are dues-paying Charterholders in good standing.													
														
														
Global Investment Performance Standards (GIPS)														
														
GIPS apply to investment management firms in order to benefit their current and prospective clients														
														
FIRMS MUST be defined as an investment firm, subsidiary, or division held out to clients or PROSPECTIVE CLIENTS as a DISTINCT BUSINESS ENTITY.														
														
Should include all fee- and non-fee paying accounts in performance presentation														
Must present 5 years of GIPS-compliant information or less if in business for less than 5 years														
Must assign portfolios to composites before the returns are known														
Composite returns must be a asset-weighted average of component returns														
Firms may include performance figures for periods prior to January 1, 2006, that were compliant with their applicable Country Version of GIPS (CVG), together with GIPS-compliant performance figures for periods after that date														
														
When local law conflicts with GIPS, must comply with local law and report conflict in report														
When the firm has discretion over the selection of sub-advisors, the firm must disclose portfolios managed by subadvisors in its composites														
Brief presentation is acceptable, as long as details are offered to all investors, upon request														
														
Key Characteristics														
Definition of "the firm" (unique business unit)														
Fair representation and full disclosure														
Input data must be accurate														
No partial compliance														
Follow local law when it conflicts with GIPS, but disclose conflict														
														
Requirements of GIPS														
Must provide a compliant presentation to all prospects														
Must provide, to clients requesting it, a compliant presentation and a composite description for any composite included on the firm's list														
For joint marketing, clearly distinguish non-compliant firms from compliant firms														
If a firm changes its organization, historical composite results cannot be changed														
List discontinued composites for at least 5 years														
Must document, in writing, policies and procedures the firms uses to comply with GIPS.														
When regulations in a GIPS-compliant firm's home country conflict with GIPS, the firm must foollow any applicable country-specific regulation and disclose the conflict in the GIPS-compliant presentation														
														
														
Compliance Statement														
"[company name] has prepared and presented this report in compliance with the Global Investment Performance Standards (GIPS&reg;)."													

													
Total firm assets includes total market value of discretionary and non-discretionary assets, including fee-paying nad non-fee paying accounts														
Composites must include all fee-paying, discretionary portfolios														
														
A composite includes all discretionary, fee-paying portfolios that are managed according to the same strategy, objective, or mandate. Non-discretionary portfolios are not included. The firm must choose the composite in which each portfolio will be included on an ex-ante basis (prior to any investment results) according to predetermined criteria, so that the firm cannot selectively include only the best-performing portfolios in a composite. 														
														
														
														
														
Major Sections of GIPS														
1.) Fundamentals of Compliance														
2.) Input Data														
3.) Calculation methodology														
4.) Composite construction														
5.) Disclosures														
6.) Presentation and reporting														
7.) Real estate - applies to most real estate investments, regardless of the degree of leverage or the degree of management by the firm														
8.) Private equity														
														
Compliance with GIPS														
Verification is not required														
Verification can be performed by an independent 3rd party only														
Must be in whole compliance with GIPS to claim compliance														
Cannot claim partial compliance														
														
Verification must be applied on a firm-wide basis; there is no such thing as verification of results for a single composite or portion of the firm's performance. A verification report must be provided upon request, only. Verification must be performed by an independent third party, which does not have to be a public accounting firm. 														
														
														
														
Presenting GIPS-compliant performance only since the firm's inception is acceptable. Five years is the minimum if the firm has been in existence five years or more. 														
														
														
The firm must add annual performance results each year going forward up to a minimum of ten years of performance history.														
														
