---
title: "CFA Level 1: Quantitative Methods"
description: ""
date: "`r Sys.Date()`"
categories:
- CFA Level 1
tags:
- Quantitative Methods
output:
      blogdown::html_page:
            toc: true
summary: "Quantitative methods covers statistical topics including descriptive statistics, hypothesis testing, and more."
thumbnail: ""
---


## Data Types							

_"NOIR" (French for "black")_
* Nominal - categorize, but do not rank			
* Ordinal - categorize and rank					
* Interval - difference between scale values equal	
* Ratio - abolute zero		

## Descriptive Statistics							
* Involves describing data based on particular metrics

## Inferential Statistics

* Involves making inferences about popolations based on samples												Statistical Inference (forecasts, estimates.)														
Estimation														
Hypothesis Testing														
														
Leptokurtic Distribution					More peaked, fatter tails (pinch the normal distribution)									
More peaked than normal distribution (excess Kurtosis > 0)														
Larger tails (fatter tails)														
														
Platykurtic Distribution					Less peaked, compressed tails (press down on normal distribution)									
Less peaked than normal distribution (excess Kurtosis < 0)														
Smaller tails														
														
Returns														
														
Arithmetic Mean vs. Geometric Mean														
The arithmetic mean is the best estimate of a single period's return.														
The geometric mean is the best estimate of future multi-year annual compound returns.														
														
Money-Weighted Return														
IRR on a series of cash flows														
														
Time-weighted return														
1. Price the portfolio immediately prior to any significant addition or withdrawal of funds.  Break the overall evaluation period into subperiods based on the dates of cash inflows and outflows.														
														
2. Calculate the holding period return on the portfolio for each subperiod.														
3. Link or compound holding period returns to obtain an annual rate of return for ht year (the time-weighted rate of return for the year). If the investment is for more thant one year, take the geometric mean of the annual returns to obtain the time-weighted rate of return over that measurement period.														
														
														
														
Assume dividends are not reinvested!														
														
Money Market														
The market for short-term debt (t-bills, commercial paper, etc.)														
														
T-bills are quoted on a bank-discount basis.														
														
Bank-Discount Yield														
Pure discount securities such as T-bills are quoted differently than government bonds														
														
			??? based on face value, not investment price											
			??? based on 360-day year											
	D = discount		??? assumes simple interest											
	F = face value													
	t = days to maturity													
														
Holding Period Return				??? based on any length of time										
				??? based on one cash payment during life										
				??? purchase price and sale price must include Accrued Interest (for bonds)										
														
				Accrued interest = Annual Coupon/2*time held by seller/total time in payment period										
Effective Annual Yield														
														
														
														
Money-Market Yield (CD equivalent yield)				Computed on the purchase price, not Face Value										
														
														
														
														
														
														
Bond-Equivalent Yield														
														
														
														
Time-Weighted Rate of Return														
Note: Dividends are assumed to be contributed by fund manager														
Note: Dividends are assumed to be held by investor (not reinvested)														
														
Position of a Percentile														
Ly = (n+1)(y/100)														
														
Probability														
														
Empirical Probability														
Based on historical outcomes														
For accuracy, relationships must be stable through time														
														
Subjective Probability														
Based on personal judgment														
														
A Priori Probability														
Based on logical analysis, reasoning														
Based on counting methods and equally-likely potential outcomes														
														
Time-Series - accross time														
Cross-Sectional - among units at a given point in time														
														
Expected Operating Costs: Operating Costs (Y-hat) = fixed costs (y-intercept)+variable costs/unit(slope)*Number of units produced														
														
Basis Point: 100 basis point = 1%														
														
														
														
														
					**Divide by "n-1" for samples									
														
Variance of Portfolio														
														
														
														
														
														
Correlation Coefficient														
??? A measure of "linear" comovement														
??? A standardized measure of covariance														
??? Correlation ranges between -1 and +1														
														
														
														
Labeling														
Multinomial Formula														
Number of ways to label k items out of n items with n1 of the first type, n2 of the second type, etc.														
														
														
														
														
Combination														
A special type of the multinomial with 2 labels (binomial model)														
														
Shortfall Risk														
Risk that a return will fall below a specifided target level														
														
Safety-First Rule														
SFRatio														
														
														
														
	If returns are normally distributed, the safety-first optimal portfolio maximizes the safety-first ratio (SFRatio).													
	The farther from the limiting return, the greater the spread between E(RP) and RL.													
														
Price Relative														
														
														
														
Continuously Compounded Return														
														
														
														
														
														
														
Independent and Identically Distributed (IID)														
Key assumption for asset returns														
Independence - investors cannot use past returns to predict future returns (i.e. weak-form market efficiency)														
Indentical Distribution - mean and variance do not change with time														
														
Annualizing														
Annualizing is often done on the basis of a 250 days in a year, the approximate number of days markets are open for trading.  (p. 452)														
														
Volatility														
The instantaneous standard deviation.														
														
Monte Carlo Simulation														
A simulation of potential outcomes ("what ifs") with time														
Used to assess risk														
Consists of multiple simulations of outcome using predetermined probability distributions. 														
Each simulation trial involves a drawing of random values														
Uses time increments and general assumptions about risk factors (growth, volatility, etc.)														
Cannot provide the insight that analytic methods can!														
														
Asian Call Option														
European-style option with value at maturity equal to difference between the stock price at maturity and the average stock price during the life of the option or $0, whichever is greater.														
														
														
Hedging Horizon														
Time span over which the hedging position will be maintained														
														
Lookback Call Option														
A call option with value at maturity equal to the stock value at maturity less the minimum value of the stock during the lift of the option prior to maturity, or zero, whichever is greater.														
														
														
Statistical Inference														
Hypothesis Testing (testing validity of parameters)														
Estimation (estimation of parameters)														
														
Sampling Bias														
Data Mining														
??? Out-of-Sample Test: using a sample that does not overlap the time period of the variable under consideration														
??? Intergenerational Data Mining: repeatedly using data produced by prior researchers until a pattern is discovered														
??? A data-mining bias occurs when variables are added to an analysis without any predictive merit (i.e., there is no causal relationship for adding the variables). The variables are not added to enhance prediction, but to thwart the predictive relationship between other variables.														
														
Sample Selection Bias														
Using data availability as a criteria for sampling														
														
Survivorship Bias														
Excluding data that is discontinued (defaulted firms)														
														
Look-ahead Bias														
Using data that is not currently available to every market participant														
														
Time-period Bias														
Using data that is inherently influenced by a specific time-period that skews the results														
														
Estimators														
														
"UEC"														
														
Unbiased														
The expected value of the estimator equals the value of the parameter														
Efficient														
The variance of the estimator is the least of all other estimators of the parameter														
Consistent														
The probability that the estimator equals the paramater increases with increasing sample size														
														
Skewed Distribution														
No Skew:      Mode = Median = Mean														
Left Skew:    Mode > Median > Mean														
Right Skew:  Mode < Median < Mean														
														
	Z	Confidence	Z	Confidence										
	1.65	90%	1	68%										
	1.96	95%	2	95%										
	2.58	99%	3	99%										
														
Confidence Interval 														
Probabilistic interpretation:  __% of the resulting confidence intervals will, in the long run, contain the population parameter														
Practical interpretation:  We are __% confident the given confidence interval contains the population parameter														
														
Total Probability Rule														
Pr(A) = Pr(A|B)Pr(B) + Pr(A|C)Pr(C)														
														
Addtion Rule of Probability														
Pr(A or B) = Pr(A) + Pr(B) - Pr(A and B)														
														
Multiplication Rule of Probability														
Pr(A and B) = Pr(A)Pr(B)														
														
Steps in Hypothesis Testing														
1. State hypothesis														
2. Decide on test statistics and probability distribution														
3. Decide on significance level														
4. Decide on decision rule														
5. Collect data and calculate test statistic														
6. Make statistical decision														
7. Make economic decision														
														
Power of  a Test														
The probability of rejecting a false null hypothesis														
Power = 1-?? = 1-Pr(Type II error)														
														
Labeling														
How many ways can k labels can be assigned to n items														
The number of items that receive label 1 is n1, where n1+n2+n3+.+nk = n														
														
														
														
														
														
Test for Population Mean (Z-stat)														
Assumptions:														
Known variance (or unknown if n>30)														
Normal distribution (or nonnormal if n>30)														
														
Test for Population Mean (T-Stat)														
Assumptions:														
Unknown variance and...														
Either														
1. sample is large (n>30) or...														
2. sample is small, but the population is at least approximately normally distributed														
														
Test of Mean Differences (T Statistic)														
Assumptions:														
Normally distributed populations														
Unknown population variances														
Test for Difference Between Means (t-stat)														
Assumptions: 														
Normally distributed populations,														
Independent populations														
Population variances unknown, but assumed equal														
														
														
														
														
														
														
df = n1+n2-2														
														
														
														
														
														
Assumptions:														
Normally distributed populations														
Independent populations														
Unequal and unknown populatino variances														
														
														
														
														
														
														
														
														
														
														
														
														
														
In majority of cases, the T-test is used!														
														
Assumptions:														
Normally distributed populations														
Dependent populations														
														
														
														
														
														
Stocks are generally considered to be dependent (both rely on market returns)														
														
		Test Statistic												
When sampling from a:		Small Sample	Large Sample											
		n<30	n>30											
Normal distribution, known variance		z	z											
														
Normal distribution, unknown  variance		t	t or z											
														
Nonnormal distribution, known variance		not available	z	Central Limit Theorem										
														
Nonnormal distribution,  unknown variance		not available	t or z	Central Limit Theorem										
														
														
Types of Risk														
Default risk - risk that a security will lose value due to a firm's default														
Liquidity risk - risk of receiving less than the fair value for an asset if it must be sold quickly														
Maturity risk - risk of higher volatility of longer maturity instruments (particularly with bonds)														
														
RRORbond = real risk-free rate + inflation premium + default risk premium + liquidity premium + maturity premium														
														
Test for Variance (1 population - ??2)														
Assumptions:														
Normally distributed population														
??2 distribution approaches the normal distribution as the sample size increases														
														
														
														
														
Test for Equality of Variances (2 populations - F-dist)														
Assumptions:														
Normally distributed populations														
Independent distributions														
Rejection region is in the right tail of the F-distribution (if s21 is the greater sample variance)														
														
														
														
														
Power of a Test														
1-P(Type II Error)														
  														
Technical Analysis														
														
Assumptions:														
Value is determined by supply and demand														
Supply and demand is driven by both rational and irrational behavior														
Prices move in trends that persist for long periods														
Causes of changes in supply and demand are difficult to determine														
														
Main challenge to technical analysis is the EMH														
Fundamentalists look for reasons why prices should change and realize the change when they find a reason for it to change														
EMH theory contends that prices adjust quickly to new information														
Technical analysts contend that prices adjust slowly to new information														
														
Almost without exception, EMH studies using autocorrelation and runs tests have found no evidence that prices move in trends. 														
														
Strategies								 						
Contrarian - most investors are wrong, so do the opposite														
Follow the smart money - "jumping on the bandwagon"														
														
Indictors														
Momentum indicators - focus on direction of market														
Price- and volume-based indicators - focus on market data														
														
														
Contrarian Rules														
1.) Cash position of mutual funds - need for liquidity (mutual fund ratio = mutual fund cash / total fund assets; a ratio > 11% suggests MF managers are bearish; a ratio < 4% suggests MF managers are bullish)														
2.) Investor credit balances in brokerage accounts - need for liquidity (credit balances are uninvested cash)														
3.) Opinions of investment advisory services - relative view of analysts														
4.) Over-the-counter vs. NYSE volume - Over-the-counter trading is more speculative														
5.) CBOE put/call ratio - puts outstanding/calls outstanding														
5.) Stock index futures - observe expected price growth														
														
Smart Money Rules														
Confidence index = quality bond yields/average bond yields														
														
In periods of confidence, investors sell high-quality bonds (increasing their yields) and buy lower-quality bonds (decreasing their yields), decreasing the yield spread														
														
In periods of pessimism, investors buy high-quality bonds (decreasing their yields) and sell lower-quality bonds (increasing their yields), increasing the yield spread														
														
														
T-bill-Eurodollar yield spread - measures international crises and use of U.S. safe havens														
Debit balances in brokerage accounts (margin debt)														
														
Momentum Indicators														
Breadth of market														
Stocks above their 200-day moving average														
														
Stock Price and Volume Techniques														
Dow Theory - stock prices move in trends														
Importance of volume - Price changes on low volume tell us little.  Price changes on high volume tell us whether suppliers or demanders are driving the change.														
														
Support and resistance levels														
Price Channels														
														
Relative Strength (RS) - RS = stock price / market index value														
														
Underlying technical analysis are the following assumptions:														
1) Values, and thus prices, are determined by supply and demand.														
2) Supply and demand are driven by both rational and irrational behavior.														
3) Security prices move in trends that persist over long periods.														
4) While the causes of changes in supply and demand are difficult to determine, the actual shifts in supply and demand can be observed in market price behavior.														
														
The major challenge to technical analysis is the efficient market hypothesis (EMH).														
														
Fundemantalists believe they  can forecast value changes by analyzing earnings and other publicly available data. 														
Fundamentalists belive prices adjust quickly.														
EMH advocates believe the price adjustment to new information happens almost instantaneously.														
Fundamentalists, through their research, look for changes in the basis of value, which eventually leads to change in the supply and demand for the stock.														
Technicians look for evidence of changes in supply and demand through market signals and indicators.														
