---
title: "CFA Level 1: Ethical and Professional Standards (part 1)"
author: ''
date: "`r Sys.Date()`"
slug: cfa-level-1-ethical-and-professional-standards-part-1
categories:
- Ethical and Professional Standards
tags:
- CFA Level 1
output:
      blogdown::html_page:
            toc: true
summary: "Ethics is a commonly failed topic in the CFA exams. It can be quite tricky, so it is critical to thoroughly understand the topic. We hope our notes help you grasp the main points."
thumbnail: ''
---


## Professional Conduct Program (PCP)					

* If a Designated Officer determines that a sanction against a member is warranted, the member must either accept the sanction or face a hearing by a panel of CFA Institute members.
* Members who provide confidential information that is solicited by  PCP staff is not in violation of the Standard III(E) Preservation of Confidentiality.

## Disciplinary Review Committee (DRC)

* The DRC is responsible for the enforcement of the CFA Institute Code of Ethics and Standards of Practice in an effort to maintain the integrity of CFA Institute membership and the CFA designation.								
										
## Primary Principles of CFA Institute Bylaws and Rules of Procedure

1. Fair Process					
2. Confidentiality of proceedings

## Code of Ethics		

1. Act with Integrity, Competence, Diligence, and Respect with all affected parties						
2. Place the integrity of the profession and interest of clients above personal interest	
3. Use Reasonable care when giving advice, taking advice, and conducting investment analysis				
4. Practice and encourage others to practice in a professional and ethical manner that will promote the profession		
5. Promote the integrity of, and uphold the rules governing, capital markets
6. Maintain and improve professional competence

## Standards of Professional Conduct	

i. Professionalism						
ii. Integrity of Capital Markets					
iii. Duties to Clients	
iv. Duties to Employers						
v. Investment Analysis, Recommendations, Actions
vi. Conflicts of Interest
vii. Responsibilities as a CFA Instute Member or CFA Candidate

## Professional Standards	

### I - Professionalism
### I(A) - Knowledge of the Law
    
* Reporting Violations:					
    1. Inform employer's compliance department and supervisor and attempt to remedy the solution
    2. Dissociate from activity (Resignation or reassignment)
    3. Inform legal or regulatory authorities
* Must comply with the stricter of the law, rule, or regulation
* Must not knowingly participate or assist in and, must dissociate from any violation of such laws, rules, or regulations
*  Members or Candidates can participate in a violation simply by having knowledge of the violation and not taking action to stop it
* Ignorance of a rule or law is not a sufficient defense
* Don't have to report violations of laws or the Code and Standards to either the CFA Instute or governmental authorities, unless required by law					
* Must disassociate from any illegal activity and actively urge the firm (either an immediate supervisor or a compliance officer) to cease any conduct that violates the law or an applicable regulation or standard. Inaction might be judged, (even in a court of law), as participating or assisting, which violates the Standard.
 
### III(B) - Independence and Objectivity
            + Must use reasonable care and judgment to achieve and maintain independence and objectivity
            + Must not offer, solicit, or accept any gift, benefit, compensation, or consideration that reasonably could be expected to compromise their own or another's independence and objectivity
            + Gifts must be disclosed to the member's employer in any case, either prior acceptace, if possible, or subsequently.
            + No requirement to notify "all related parties," because it is the obligation of the employer to determine if loyalties to other clients will be affected. After permission is received from employer, receipt of gift is acceptable.
            + Gifts that are offered to demonstrate a firm's product/service are acceptable and need not be disclosed
            + Must act as an independent source of financial incite, not reliant on other professionals for decisionmaking
            + Must not accept gifts that are hard to come by and most likely expensive since they pose a potential threat to objectivity
            + Gifts that are accepted for prior performance and not contingent on future performance don't threaten objectivity
            + Gifts that are contingent on future performance must be authorized by a supervisor or compliance department
            + Gifts of significant value can be accepted as long as an employer authorizes acceptance AND the gifts will not threaten duty to other clients
            + Gifts that are a part of the required itiniery and not easily substitutable (such as special flights) can be accepted
            + Reasonable payment for hotel rooms and chartered flights is acceptable.  Irrelevent or lavish hospitality could compromise objectivity and should be avoided.
            + Gifts that are given to inspire high performance are allowable, but if it is contingent on future performance, employer consent is required by supervisor or compliance department
            + Must not participate in oversubscribed IPOs
            + When providing analysis of a security AND maintaining ownership of the security, whether self-managed or not, member must disclose the ownership to appropriate clients.
            + Members may accept modest gifts, which it specifically defines as being anything worth less than US$100, as long as they do not affect objectivity.
            + Be sure there are effective "firewalls" between research/investment managemetn and investment banking activities
            + Do not confine research to discussions with company management; use several sources
      c. Misrepresentation
            + Must not knowingly make any misrepresentations relating to professional activities
            + All sources in an analyst's report must be documented - except factual information published by recognized financial and statistical reporting services
      d. Misconduct
            + Must not engage in any professional conduct involving dishonesty, fraud, or deceit or commit any act that reflects adversely on professional reputation, integrity, or competence
            + Standard I(D) Misconduct primarily covers professional activities but also refers to any activities (professional or personal) that reflect adversely on members' professional competence, integrity, or reputation.
            + Must not use CFA Instute's Professional Conduct Program to settle personal, political, or other disputes not related to professional ethics
            
ii. Integrity of Capital Markets
      a. Material Nonpublic Information
            + Must not act or cause others to act on material nonpublic information (information that would likely have an impact on the price of a security or that reasonable investors would want to know before making an investment decision)
	      + Must make good-faith effort to prevent the transfer and misuse of material nonpublic information
	      + Disclosure in widely-used news sources would likely cause traders to act
	      + __Mosaic Theory__: nonmaterial, nonpublic information combined with research can be used to make investment decisions and recommendations
	      + An analyst conference call is not public disclosure.
	      + Information is nonpublic until it has been made available to the marketplace
	      + Recommended to restrict proprietary trading, but still make unsolicited trades
	      + Should provide an information firewall to limit transmittal of material nonpublic information within firm
            + Common knowledge is regarded as "public" information
            + Should first make reasonable efforts to achieve public dissemination and then, if necessary, disclose information only to designated supervisory and compliance personnel.
	      + A firm's internal information "firewall" should include a reporting system in which authorized personnel review and approve interdepartmental communications.
      b. Market Manipulation						
	      + Must not engage in practices that distort prices or artificially inflate trading volume with the intent to mislead market participants		
	+ Must not spread false information
	+ Whatever the motivation, the intent must not be to deceive market participants
iii. Duties to Clients
      a. Loyalty, Prudence, and Care
            + Have a duty of loyalty, act with reasonable care, and exercise prudent judgment
            + Must act for the clients' interests and place their interests before their employer's and own self-interest
            + Make investment decisions in the context of the entire portfolio
            + Allowed to make preparations for future employment while still employed, as long as it doesn't affect loyalty to current employer
            + Soft dollar commissions must be used to benefit the client
            + Voting on proxies is only required for nonroutine issues with material impact
            + Client brokerage commissions must not be directed to pay for the investment manager's operating expenses.
      b. Fair Dealing
            + Must deal fairly and objectively when providing investment services
            + Must fairly disseminate investment information (to all clients) and trade for clients' accounts first
            + May accept unsolicited trade requests after notifying (verbal or written) a client of changes in recommendations before processing trades
            + Can offer different levels of service to clients, but must disclose this to all clients
            + Must provide reasonably sufficient time for clients to trade before making personal trades
            + Recommended to limit the number of people who know about changes to recommendations
            + Should forgo any sales to themselves or their immediate families to free up additional shares of oversubscribed stock issues for clients
            + Employers should compare personal transactions of employees with those of clients on a regular basis regardless of the existence of a requirement by any regulatory organization.
      c. Suitability
            + Must make reasonable inquiry into a client's investment experience, objectives and constraints, and regularly update this information
            + Suitability is judged in an overall portfolio context and not on a security-by-security basis
            + Make sure investment recommendations conicide with clients' written objectives
            + Brief communications are permitted (as brief as a list of recommended securities) as long as these recommendations are supported by appropriate background reports that can be made available to clients upon request. Sending a recommended list to all clients, even though not every recommended security is suitable for them, is not a violation of the Standards.
            + For unsolicited trades that conflict with investment objectives, must receive affirmative statement acknowledging that suitability is not a concern
            + Must updated Investment Policy Statement (IPS) at least annually
            + Suitability does not become a concern until an investor has taken action
            + For unsolicited trades that conflict with investment recommendations, must advise the client of the change in recommendation before accepting the order
            
<hr>

<a id="nav__prev" href="../cfa-study-topics">Topics List</a>

<a id="nav__next" href="../cfa-level-1-ethical-and-professional-standards-part-2">Next</a>

<br>