---
title: "CFA Level 1: Quantitative Methods (part 2)"
slug: cfa-level-1-quantitative-methods-part-2
description: ""
date: "`r Sys.time()`"
categories:
- CFA Level 1
tags:
- Quantitative Methods
output:
      blogdown::html_page:
            toc: true
summary: "Quantitative methods covers statistical topics including descriptive statistics, hypothesis testing, and more."
thumbnail: ""
---

***

## Probability          

### Empirical Probability	

* Based on historical outcomes					
* For accuracy, relationships must be stable through time

### Subjective Probability		

* Based on personal judgment			
						
### A Priori Probability            

* Based on logical analysis, reasoning
* Based on counting methods and equally-likely potential outcomes

### Time-Series - across time		

### Cross-Sectional - among units at a given point in time	
								
Expected Operating Costs: Operating Costs (Y-hat) = fixed costs (y-intercept) + variable costs/unit(slope)*Number of units produced

## Basis Point 

* 100 basis points = 1%

**Divide by "n-1" for samples						
						
Variance of Portfolio														
Correlation Coefficient														
* A measure of "linear" comovement					
* A standardized measure of covariance				
* Correlation ranges between -1 and +1				
									
Labeling														
Multinomial Formula														
Number of ways to label k items out of n items with n1 of the first type, n2 of the second type, etc.														
														
## Combination		

* A special type of the multinomial with 2 labels (binomial model)							

## Shortfall Risk		

* Risk that a return will fall below a specifided target level

## Safety-First Rule          

SFRatio														
	If returns are normally distributed, the safety-first optimal portfolio maximizes the safety-first ratio (SFRatio).													
	The farther from the limiting return, the greater the spread between E(RP) and RL.													
														
Price Relative														
														
														
														
Continuously Compounded Return														
														
														
														
														
														
														
Independent and Identically Distributed (IID)														
Key assumption for asset returns														
Independence - investors cannot use past returns to predict future returns (i.e. weak-form market efficiency)														
Indentical Distribution - mean and variance do not change with time														
														
Annualizing														
Annualizing is often done on the basis of a 250 days in a year, the approximate number of days markets are open for trading.  (p. 452)														
														
Volatility														
The instantaneous standard deviation.														
														
## Monte Carlo Simulation           

* A simulation of potential outcomes ("what ifs") with time	
* Used to assess risk						
* Consists of multiple simulations of outcome using predetermined probability distributions		
* Each simulation trial involves a drawing of random values	
* Uses time increments and general assumptions about risk factors (growth, volatility, etc.)				
* Cannot provide the insight that analytic methods can!	

Asian Call Option

European-style option with value at maturity equal to difference between the stock price at maturity and the average stock price during the life of the option or $0, whichever is greater.	

## Hedging Horizon            

* Time span over which the hedging position will be maintained

## Lookback Call Option		

* A call option with value at maturity equal to the stock value at maturity less the minimum value of the stock during the lift of the option prior to maturity, or zero, whichever is greater.

<hr>

<a id="nav__prev" href="../cfa-level-1-quantitative-methods-part-1">Previous</a>

<a id="nav__next" href="../cfa-level-1-quantitative-methods-part-3">Next</a>

<br>
	
														
