---
title: "CFA Level 1: Ethical and Professional Standards (part 2)"
author: ''
date: "`r Sys.Date()`"
slug: cfa-level-1-ethical-and-professional-standards-part-2
categories:
- Ethical and Professional Standards
tags:
- CFA Level 1
output:
      blogdown::html_page:
            toc: true
summary: ""
thumbnail: ''
---


## Professional Standards (cont)  
  
iii. Duties to Clients  
      a. Loyalty, Prudence, and Care  
            + Have a duty of loyalty, act with reasonable care, and exercise prudent judgment  
            + Must act for the clients' interests and place their interests before their employer's and own self-interest  
            + Make investment decisions in the context of the entire portfolio  
            + Allowed to make preparations for future employment while still employed, as long as it doesn't affect loyalty to current employer  
            + Soft dollar commissions must be used to benefit the client  
            + Voting on proxies is only required for nonroutine issues with material impact  
            + Client brokerage commissions must not be directed to pay for the investment manager's operating expenses  
      b. Fair Dealing  
            + Must deal fairly and objectively when providing investment services  
            + Must fairly disseminate investment information (to all clients) and trade for clients' accounts first
            + May accept unsolicited trade requests after notifying (verbal or written) a client of changes in recommendations before processing trades
            + Can offer different levels of service to clients, but must disclose this to all clients
            + Must provide reasonably sufficient time for clients to trade before making personal trades
            + Recommended to limit the number of people who know about changes to recommendations
            + Should forgo any sales to themselves or their immediate families to free up additional shares of oversubscribed stock issues for clients
            + Employers should compare personal transactions of employees with those of clients on a regular basis regardless of the existence of a requirement by any regulatory organization
      c. Suitability
            + Must make reasonable inquiry into a client's investment experience, objectives and constraints, and regularly update this information
            + Suitability is judged in an overall portfolio context and not on a security-by-security basis
            + Make sure investment recommendations conicide with clients' written objectives
            + Brief communications are permitted (as brief as a list of recommended securities) as long as these recommendations are supported by appropriate background reports that can be made available to clients upon request. Sending a recommended list to all clients, even though not every recommended security is suitable for them, is not a violation of the Standards.
            + For unsolicited trades that conflict with investment objectives, must receive affirmative statement acknowledging that suitability is not a concern
            + Must updated Investment Policy Statement (IPS) at least annually
            + Suitability does not become a concern until an investor has taken action
            + For unsolicited trades that conflict with investment recommendations, must advise the client of the change in recommendation before accepting the order
      d. Performance Presentation
            + Must make reasonable efforts to ensure that performance presentation is fair, accurate, and complete
            + Must include terminated accounts as part of historical performance
            + Consider the sophistication of audience
            + No minimum performance history is required
            + Simulated results can be reported, as long as this is disclosed
            + Must disclose if results are realized under the authority of another firm
            + Footnote disclosure is not enough to comply with this standard
            + Recommended to disseminate new recommendations to all clients who express an interest or for whom the investment is suitable
            + Must cite specific source of investment performance (e.g. "investment experts" is too vague)
            + Recommended to use GIPS in performance presentation
      e. Preservation of Confidentiality
            + Must keep client information confidential unless (1) it involves illegal activities, (2) disclosure is required by law, or (3) the client permits disclosure
            + Must report illegal activity to employer first and then, if necessary, seek outside counsel
            + Can disclose confidential information to authorized fellow employees to ensure that a manager is aware of a client's needs and concerns
            + Must not disclose confidential information, even if it benefits the client
iv. Duties to Employers
      a. Loyalty
            + In matters of employment, must act for the benefit of their employer and not deprive their employer of advantage of their skills and abilities
            + May use prior knowledge and professional skill in new jobs
            + Must not misappropriate trade secrets or solicit employer's clients before leaving, unless written consent from employer is received
            + No requirement to place employer interests above family and other personal obligations
            + Whistleblowing is not a violation of the Standards, unless it is done to promote personal gains instead of to protect clients or markets
	        + Both employees and independent contractors must abide by the Standards
      b. Additional Compensation Arrangements
            + Must not engage in activities that might reasonably create a conflict of interest with an employer, unless written request and consent from all parties is obtained
	        + Independent practice for compensation is allowed if a written notification is provided to the employer fully describing all aspects of the services, including compensation, duration, and the nature of the activities and if the employer consents to all terms of the proposed independent practice before it begins
	        + Accepting work that competes with employer is acceptable, but only after written notification is received from employer
      c. Responsibilities of Supervisors
            + Must make reasonable efforts to detect and prevent violations of applicable laws, rules, regulations, and the Code and Standards by anyone subject to supervision or authority
            + Must take action to prevent future violations
            + Must incorporate and disseminate details of a Professional Conduct Evaluation to all appropriate employees
            + If a member cannot discharge compliance responsibilities because of a poor compliance system, the member should decline in writing to accept supervisory responsibility until the firm adopts an adequate system
v. Investment Analysis, Recommendations, and Action
      a. Diligence and Reasonable Basis
            + Must exercise diligence, independence, and thoroughness in all investment activity
            + Must have a reasonable and adequate basis for investment actions
            + Use of an unfamiliar investment model is not a violation, unless there is a reasonable suspicion of inadequacy
	        + When using third-party analysis, must review assumptions used and evaluate the objectivity and independence of recommendations
	        + Opinon of another analyst is not an reasonable basis for a recommendation
      b. Communication with Clients and Prospective Clients
            + Must disclose to clients the basic format and general principles of the investment processes
            + Must promptly disclose changes to the basic format and general principles
            + Must distinguish between fact and opinion
            + Must notify (verbal or written) of material changes in investment strategy and methods
            + Personal bankruptcy does not compromise professional reputation, so it is not a required disclosure
            + Must disclose general strategy of investment management; trade details need not be disclosed
      c. Record Retention
            + Must develop and maintain appropriate records to support investment-related actions and communication with clients and prospective clients
            + CFA Institute recommends 7 years of record retention
            + The firm is generally responsible for record-keeping
vi. Conflicts of Interest
      a. Disclosure of Conflicts
            + Must make full and fair disclosure of matters that could reasonably be expected to impair their independence and objectivity or interfere with respective duties to clients, prospective clients, and employers
            + Must ensure that disclosures are prominent and delivered in plain language, and communicate the relevent information effectively
            + Ownership of an analyzed stock is not a violation, but significant ownership could reasonably be expected to impair judgment
            + Best practice is to disclose ownership of a covered stock to the employer and in the investment report
      b. Priority of Transactions
            + Investment transactions for clients and employers must take precedence over personal trades for personal benefit
            + Must not trade shares (client or personal shares) before issuing a recommendation report
	        + Recommended to avoid participating in IPOs to avoid the appearance of conflict											
	Disclosure is not enough to comply with this standard and the execution price is not relevant
      c. Referral Fees
            + Must disclose appropriately to employer, clients, and prospective clients, as appropriate, any compensation received from (or paid to) others for the recommendation of products or services
            + Must disclose referral agreements, whether external or internal 
            + Referral fees that are commonly present and reasonably expected to be paid by employer to employee need not be disclosed
vii. Responsibilities as a CFA Institute Member or CFA Candidate
      a. Conduct as Members and Candidates in the CFA program
            + Must not engage in any conduct that compromises the reputation or integrity of CFA Institute or the CFA designation or the integrity, validity, or security of the CFA examinations
            + Preparation of an attempt to violate the integrity of an exam challenges the integrity of the CFA program, even if the action is not carried out
      b. Reference to CFA Institute, the CFA designation, and the CFA program
            + Must not exaggerate the meaning of the CFA designation or suggest it's membership gives analysts superior performance potential
            + Must not use "CFA" as a noun
            + To Be considered a candidate, individuals must be registered to take the next schedule CFA exam
            + Allowed to express negative opinions about the CFA Institute or CFA program
            + Use of the CFA designation to those who have passed all three levels of the CFA Program, have received their charters, and are dues-paying Charterholders in good standing.
            

<hr>

<a id="nav__prev" href="../cfa-level-1-ethical-and-professional-standards-part-1">Back</a>

<a id="nav__next" href="../cfa-study-topics">Topics List</a>

<br>
