---
title: "CFA Level 1: Equities"
date: ''
slug: cfa-level-1-equities
categories: 
- Equities
- CFA Level 1
tags:
- Equities
excerpt: "The CFA level 1 exam covers equities (stocks). The topic Equities covers such things as types of stock markets, order types, indexes, market efficiency, and more. Study with our free notes."
output:
      blogdown::html_page:
            toc: true
---

# _Equities_

## Types of Orders								
* **Market Orders** - Buy or sell orders that are executed at the current price (guarantees execution, but not price)
* **Limit Orders** - Buy or sell orders when the stock price passes a desirable limit (guarantees price or better, but not execution)
  + **Limit Buy** - purchase a stock if and when it can be bout at-or-below a certain price
  + **Limit Sell** - sell a stock if and when it rises above a certain price
***Note:*** A collection of limit orders is called the limit order book.
* **Stop Orders** - buy or sell orders when the stock price passes an undesirable limit
  + **Stop-Loss** - sell a stock if its price falls below a certain price (guarantees execution, but not price)								
  + **Stop-Buy** - purchase a stock if its price rises above a certain price			
*Caution:* Stops are not a guarantee of getting the desired entry/exit points.			

## Financing 
* **Internal Financing**
  + Customer Deposits	
  + Retained Earnings	
* **External Financing**	
  + Short-term debt	
  + Long-term debt	
  + Common stock	
  + Preferred stock	

## Underwriting
* **Rule 415 (Shelf Registrations)**									
  + Allows large firms to register security issues and then sell them piecemeal during the following two years									
  + Benefits: Flexibility, Lower registration fees, better competitive bids from underwriting firms
* **Underwriting Services**									
  + Origination									
  + Risk-bearing									
  + Distribution								
* **Underwriting of bonds**
  + Competiitive bid									
  + Negotiated sales (most common)									
  + Private placements									
* **Underwriting Equity**								
  + Negotiated Sales									
  + Competitive Bid									
  + Best-efforts 									

## Markets
* **Call Market**
  + A market in which all bids and asks are gathered and the stock is traded at a single price that attempts to satisfy most of the orders ("clears the market")
* **Continuous Market**									
  + A market in which stocks are traded at any time the market is open									
***Note:*** Stocks are priced either by auction or by dealers									
									
## Short Selling									
* **Benefits of short selling**
  + Price Discovery									
  + Liquidity
  + Short sellers discover many financial frauds.
  
***Note:*** Stocks with more shorting activity tend to have poor investment fundamentals, such as low cash flow, earnings, and book value relative to price. Research suggests that short sellers distinguish between stocks with temporarily poor fundamentals and those with persistently poor fundamentals, indicating they influence prices accurately, on average.									

# Indexes/Indices

## Constructing an Index											
1. Sample
2. Weighting Sample Members
3. Computational Procedure
											
## Price-Weighted Index											
* Simple average of component prices with divisor that is adjusted for stock splits and changes in index stock representation									
											
## Market-Weighted Index
* "Capitalization-weighted" index value									
$\mathrm {\large {\text{Index value} = \sum_{i=1}^n \frac{P_{i}} {D_{adj}}}}$
* **Note:** Index returns typically focus on capital gains only!			
* A portfolio with equal number of shares of each stock in a price-weighted index will match the performance of the index assuming there are no stock splits, stock dividends or changes to the structure of the index.

## Efficient Market Hypothesis
* **Weak form Efficiency** - prices reflect all currently available market information (historical sequence of prices, rates of return, trading volume data, etc.)
* **Semi-strong form Efficiency** - prices reflect all public market and non-market information									
* **Strong form Efficiency** - price reflect all public and private market and non-market information ("perfect markets")											

## Abnormal rate of return
* Abnormal return = Actual return - expected, risk-adjusted rate of return											
											
## Tests for Market Efficiency					
* Efficiency means informationally efficient, not operationally efficient.
* Weak-form Efficiency (threatens technical analysis)
* Test for ability to use historical price and volume inforamation to earn abnormal returns (autocorrelation tests: ++---++++---)										

## Tests for independence											
* Trading rule tests											
* Semi-Strong form Efficiency (threatens fundamental analysis)											
Test for ability to use public market and non-market information to earn abnormal returns (Abnormal returns should add to zero in long run)											
											
## Return prediction studies											
* Event studies											
* Time-series tests											
* Cross-sectional tests (Security market line)									

## Strong-form Efficiency											
* Inside traders appear to earn above-average profits
* Specialists, with sole access to the limit order book, appear to earn above-average profits											
* Security analysts, as reported in Value Line and the WSJ, strongly influence prices within 2 days											
* Professional money managers underperform a buy-and-hold policy, after considering management fees and trading costs											
											
## Market Anamolies (public information - tests for Semi-strong EMH)				
* Black suggests that most anomalies result from "data mining"		
* Earnings surprises to predict returns
  + Quarterly earnings surprises are not priced as fast as semistrong EMH would suggest
* Calendar studies											
  + Unexpected returns are observed in January, beginning of week, end of weeks, etc.
* Price-earnings ratio (P/E)											
  + Stock with low P/E ratios have experienced above-market returns, while stock with high P/E ratios have experienced below-market returns
* Small firm effect					
  + Small firms consistently earned higher risk-adjusted returns than large firms, maybe due to inability of CAPM to correctly capture small-firm risk
* Neglected firms effect											
  + Companies with few analysts following them appear to have above-average returns
* Book value/Market value ratios
  + The greater the BV/MV ratio, the higher the risk-adjusted rate of return											
											
## Reasons Why Markets Should be Efficient  
* Large number of independent, profit-maximizing investors engaged in valuation
* New information comes to the market randomly
* Traders will adjust prices rapidly											
											
## EMH Conclusions								
* **Weak-form efficiency** - Empirical evidence supports the Weak-form EMH
  + Simple trading rules using historical price and volume data cannot be used to consistently produce superior returns after adjusting for transaction costs and taxes
* **Semi-strong form efficiency** - Empirical evidence mostly supports the Semi-strong EMH
  + Event studies support and time-series and Cross-sectional studies contradict Semi-strong form EMH											
* **Strong-form efficiency** - Empirical evidence does not support the Strong-form EMH	
  + Corporate insiders and market specialists have superior inside information and can consistently earn abnormal profits										* The EMH predicts that most fundamental analysis is futile
* Only analysts with unique insight receive superior returns											
											
## Role of Portfolio Managers (in a perfectly efficient market)				
1. Identify risk/return objectives
2. Develop a well-diversified portfolio
3. Reduce transaction costs											
4. Develop capital market expectations
5. Implement and update investment strategy		
											
***Note:*** The proper way to guage manager performance is to compare portfolio return to the return on a randomly selected buy-and-hold strategy of stocks within the same risk class.
											
***Note:*** When the dividend yield (D/P, payout ratio) and the bond default spread are high, risk is generally high and investors expect or require a high return on stocks and bonds
											
											
## Exchange Traded Funds (ETFs)										
* An exchange-traded fund, or ETF, is a type of closed-end mutual fund that pools assets in order to meet certain identified objectives, often matching the return of a particular index (e.g., S&P 500 Index, Russell 2000 Index, or an index representing a sector, such as gold or oil). Unlike a conventional, or open-end, mutual fund, ETFs trade throughout the day, with market arbitrage providing some level of confidence that the value of the ETF over time will track the performance of the relevant index.
* An ETF is simply a basket of securities that are publicly traded in the marketplace.
* Throughout the day, there is an "INAV," or intra-day net-asset-value, which tracks the value of an ETF on a 15-second basis and is based on the underlying constituents.
* Because INAV values can have issues, market makers and ETF sponsors maintain a separate, real-time price on their ETF.
* The real driver of liquidity in an ETF is the liquidity of the underlying assets that the ETF holds.
* Market makers, specifically authorized participants (APs), can arbitrage differences between the net-asset-value (NAV) of an ETF and the value of the underlying ETF holdings.
* At every given point in the day, an AP is calculating the cost to buy the basket of securities that form an ETF, and the cost of selling a basket of securities that form an ETF. They compare these two "theoretical" portfolios to the live net asset value of the ETF.
* The market maker can simply redeem an ETF unit
* If market makers or APs are "surprised" by a large incoming trade order, they may think an arbitrageur is trying to get the best of them, and that perhaps something is wrong with a stock in the basket or with their own internal NAV calculations of which they are not yet aware, and reflexively widen the spread.											
											
## Issuing ETFs											
1. SEC approval is required to issue ETFs, which takes many months, sometimes years
2. Alternatives to new SEC approval:				
  + Manage a portfolio of a company that already has SEC issuance clearance.
  + Buy company with ETF issuance clearance.											
											



